# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossprod_bm <- function(X_, y_, row_idx_) {
    .Call('bigSVM_crossprod_bm', PACKAGE = 'bigSVM', X_, y_, row_idx_)
}

