# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

big_svm <- function(X_, y_, row_idx_, lambda_, nlambda_, lambda_min_, pf_, gamma_, alpha_, thresh_, ppflag_, scrflag_, dfmax_, max_iter_, user_, message_) {
    .Call('bigSVM_big_svm', PACKAGE = 'bigSVM', X_, y_, row_idx_, lambda_, nlambda_, lambda_min_, pf_, gamma_, alpha_, thresh_, ppflag_, scrflag_, dfmax_, max_iter_, user_, message_)
}

crossprod_bm <- function(X_, y_, row_idx_) {
    .Call('bigSVM_crossprod_bm', PACKAGE = 'bigSVM', X_, y_, row_idx_)
}

